[package]
name = "ginkou"
version = "0.1.0"
authors = ["Lúcás Meier <cronokirby@gmail.com>"]
edition = "2018"

[dependencies]
mecab = "0.1"
rusqlite = "0.18"
structopt = { version = "0.2.1", default-features = false }